# Generated by Django 3.1.5 on 2021-01-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=2, max_length=70)),
                ('gender', models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=2)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('confirm', models.CharField(max_length=8)),
            ],
        ),
    ]
