# Generated by Django 3.1.5 on 2021-02-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
    ]
