# Generated by Django 3.1.5 on 2021-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210311_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, default='icon-contact-user@2x.png', null=True, upload_to=''),
        ),
    ]
