# Generated by Django 3.1.5 on 2021-01-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('Catagory', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
