# Generated by Django 3.1.5 on 2021-02-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=2, max_length=70)),
                ('website', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
