# Generated by Django 3.1.5 on 2021-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
