# Generated by Django 3.1.5 on 2021-02-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('appoinment', '0007_auto_20210225_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
