# Generated by Django 3.1.5 on 2021-02-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0008_booking_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Services',
        ),
    ]
