# Generated by Django 3.1.5 on 2021-02-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0010_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
