# Generated by Django 3.1.5 on 2021-03-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0011_remove_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='beautician',
            field=models.CharField(default='Arif Balvar', max_length=100),
        ),
    ]
